name: CI-CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/iit-lab:latest
  deploy:
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        working-directory: terraform
    steps:
      - uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Create credentials file
        run: |
          echo '${{ secrets.GCP_CREDENTIALS_JSON }}' > creds.json

      - name: Terraform Init
        run: terraform init -backend-config="credentials=creds.json"

      - name: Terraform Apply
        run: terraform apply -auto-approve -var="credentials_file=creds.json"

      - name: Get Terraform Outputs
        id: tf-outputs
        run: |
          echo "ip=$(terraform output -raw external_ip)" >> $GITHUB_OUTPUT
          terraform output -raw private_key > private_key.pem
          chmod 600 private_key.pem
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ steps.tf-outputs.outputs.ip }}
          username: ${{ secrets.EC2_USER }}
          key-path: private_key.pem
          script: |
            echo "Pulling latest image..."
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/iit-lab:latest
            
            echo "Stopping existing container..."
            sudo docker stop iit-lab || true
            sudo docker rm iit-lab || true
            
            echo "Running new container..."
            sudo docker run -d --name iit-lab -p 80:80 ${{ secrets.DOCKERHUB_USERNAME }}/iit-lab:latest